name: CI

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout (Descargar el repositorio)
      - uses: actions/checkout@v4
      - name: ðŸ‘¾ Generar GrÃ¡fico Pac-Man de Contribuciones
        uses: ifg/pacman-contribution-graph-action@v1 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_path: output/pacman-contribution-graph.svg
          svg_dark_path: output/pacman-contribution-graph-dark.svg
          username: antidv 

      # 4. Commit (Mejorado para manejar la ausencia de cambios)
      # Nota: Usamos 'git diff-index' para comprobar si hay archivos nuevos/modificados antes de intentar el commit.
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # AÃ±ade los archivos generados
          git add output/pacman-contribution-graph.svg output/pacman-contribution-graph-dark.svg

          # Verifica si hay cambios para commitear
          if git diff-index --quiet HEAD; then
            echo "::set-output name=pushed::false"
            echo "No hay cambios en el SVG para commitear. Saltando commit."
          else
            git commit -m "Actualiza el grÃ¡fico de contribuciones"
            echo "::set-output name=pushed::true"
          fi

      # 5. Push (Solo si hubo un commit en el paso anterior)
      - name: Push changes
        if: steps.commit.outputs.pushed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
